const SETTINGS = {
  LOYALTY_YEARS_TO_DISCOUNT: 2,
  DEFAULT_DISCOUNT_BASED_ON_PRICE: {
    MINIMUM_PRICE: 100,
    DISCOUNT: 5 / 100
  }
};

const CUSTOMER_TYPE = {
  EMPLOYEE: "EMPLOYEE",
  AFFILIATE: "AFFILIATE",
  LOYALTY: "LOYALTY"
};

const CATEGORY_TYPE = {
  GROCERY: "GROCERY"
};

const DISCOUNT_BASED_ON_TYPE = {
  [CUSTOMER_TYPE.EMPLOYEE]: 30 / 100,
  [CUSTOMER_TYPE.AFFILIATE]: 10 / 100,
  [CUSTOMER_TYPE.LOYALTY]: 5 / 100
};

export { SETTINGS, CUSTOMER_TYPE, DISCOUNT_BASED_ON_TYPE, CATEGORY_TYPE };
