const SETTINGS = {
  LOYALTY_YEARS_TO_DISCOUNT: 2,
  DEFAULT_DISCOUNT_BASED_ON_PRICE: {
    MINIMUM_PRICE: 100,
    DISCOUNT: 5 / 100
  }
};

const CUSTOMER_TYPE = {
  EMPLOYEE: "EMPLOYEE",
  AFFILIATE: "AFFILIATE",
  LOYALTY: "LOYALTY"
};

const CATEGORY_TYPE = {
  GROCERY: "GROCERY"
};

export { SETTINGS, CUSTOMER_TYPE, CATEGORY_TYPE };
